# Generated by Django 3.2.15 on 2022-09-27 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='lang',
            field=models.CharField(default='eng', help_text='Enter a language of the book (English, russian, etc...)', max_length=100),
            preserve_default=False,
        ),
    ]
