# Generated by Django 3.2.15 on 2022-10-04 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_book_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover',
        ),
    ]
