# Generated by Django 3.2.15 on 2022-10-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(height_field=1000, null=True, upload_to='covers/', width_field=800),
        ),
    ]
