# Generated by Django 3.2.15 on 2022-10-05 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20221003_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='preview',
            field=models.FileField(null=True, upload_to='pdf/'),
        ),
    ]
