# Generated by Django 3.2.15 on 2022-10-06 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_book_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='preview',
        ),
    ]
